Traceback (most recent call last):
  File "/root/venv/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/shared-libs/python3.7/py-core/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/shared-libs/python3.7/py-core/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/shared-libs/python3.7/py-core/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/shared-libs/python3.7/py-core/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/shared-libs/python3.7/py-core/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/shared-libs/python3.7/py-core/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x_indicator = "NY.GDP.PCAP.PP.CD"
y_indicator = "SP.DYN.LE00.IN"
size_indicator = "SP.POP.TOTL"
color_column = "Sub-region Name" 
indicator_list = [x_indicator, y_indicator, color_indicator]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-1f312db31cd7>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0msize_indicator[0m [0;34m=[0m [0;34m"SP.POP.TOTL"[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mcolor_column[0m [0;34m=[0m [0;34m"Sub-region Name"[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mindicator_list[0m [0;34m=[0m [0;34m[[0m[0mx_indicator[0m[0;34m,[0m [0my_indicator[0m[0;34m,[0m [0mcolor_indicator[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'color_indicator' is not defined
NameError: name 'color_indicator' is not defined

